[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[build]
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"
  node_version = "22.x"